name: React cicd
on:
    push:
        branches:
            - main
    workflow_dispatch:

jobs:

    build:

        runs-on: ubuntu-latest
        steps:
            - name: check Out
              uses: actions/checkout@v4

            - name: docker login
              run: docker login -u ${{ secrets.DOCKER_USER }} -p ${{ secrets.DOCKER_PASS }}

            - name: build image
              run: docker build -t babai12/aws_frontend .

            - name: push image 
              run: docker push babai12/aws_frontend:latest

    deploy:

      needs: build
      runs-on: self-hosted
      steps:
        - name: pull image
          run: docker pull babai12/aws_frontend:latest

        - name: delete old container
          run: docker rm -f react_container

        - name: run image
          run: docker run -d -p 5173:5173 --name=react_container babai12/aws_frontend:latest
